    - name: Installing openjdk-1.7.0
      become: yes
      yum:
        name={{ item }}
        state=latest
      with_items:
        - java-1.7.0-openjdk
        - java-1.7.0-openjdk-devel
      tags: [openjdk]

    #- name: Set the $JAVA_HOME and $PATH
    #  lineinfile: dest=/root/.bash_profile insertbefore='^export PATH' line="  {{item.line}}"
    #  with_items:
    #    - { line: 'export JAVA_HOME=/usr/java/jdk{{jdk_version}}' }
    #    - { line: 'export MIRA_ROOT=/opt/data/rg01/mira' }
