    - name: Create YARN directories for storing temporary data
      become: yes
      file:
        path={{ item }}
        state=directory
        owner=yarn
        group=hadoop
        mode=0755
        recurse=yes
      with_items: "{{YARN_LOCAL_DIR.split(',')}}"
      tags: [hadoop_create_yarn_dirs]

    - name: Create YARN directories for storing YARN logs
      become: yes
      file:
        path={{ item }}
        state=directory
        owner=yarn
        group=hadoop
        mode=0755
        recurse=yes
      with_items: "{{YARN_LOG_DIR.split(',')}}"
      tags: [hadoop_create_yarn_dirs]


    - name: Create YARN directories for container log data
      become: yes
      file:
        path={{ item }}
        state=directory
        owner=yarn
        group=hadoop
        mode=0755
        recurse=yes
      with_items: "{{YARN_LOCAL_LOG_DIR.split(',')}}"
      tags: [hadoop_create_yarn_dirs]

    - name: Create YARN directory for storing YARN PID
      become: yes
      file:
        path={{ item }}
        state=directory
        owner=yarn
        group=hadoop
        mode=0755
        recurse=yes
      with_items: "{{YARN_PID_DIR.split(',')}}"
      tags: [hadoop_create_yarn_dirs]

