    - name: Starting zookeeper
      become: yes
      become_user: zookeeper
      shell: bash -c "export ZOOCFGDIR={{ZOOKEEPER_CONF_DIR}} ; export ZOOCFG=zoo.cfg; source {{ZOOKEEPER_CONF_DIR}}/zookeeper-env.sh ; /usr/hdp/current/zookeeper-server/bin/zkServer.sh start"
      tags: [start_zookeeper]
