    - name: Create HDFS log directory
      become: yes
      file:
        path={{ item }}
        state=directory
        owner=hdfs
        group=hadoop
        mode=0755
        recurse=yes
      with_items: "{{HDFS_LOG_DIR.split(' ')}}"
      tags: [hadoop_create_hdfs_dirs]

    - name: Create HDFS diretory for storying the HDFS PID
      become: yes
      file:
        path={{ item }}
        state=directory
        owner=hdfs
        group=hadoop
        mode=0755
        recurse=yes
      with_items: "{{HDFS_PID_DIR.split(' ')}}"
      tags: [hadoop_create_hdfs_dirs]

