    - name: Install HDFS, YARN and MapReduce
      become: yes
      yum:
        name={{ item }}
        state=latest
      with_items:
        - hadoop
        - hadoop-hdfs
        - hadoop-libhdfs
        - hadoop-yarn
        - hadoop-mapreduce
        - hadoop-client
        - openssl
      tags: [base_hadoop]

    - name: Install Snappy and LZO libraries
      become: yes
      yum:
        name={{ item }}
        state=latest
      with_items:
       - snappy
       - snappy-devel
       - lzo
       - lzo-devel
       - hadooplzo
       - hadooplzo-native
      tags: [base_hadoop]
