    - name: Download EPEL repository
      become: yes
      get_url:
        url=http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-5.noarch.rpm
        dest=/tmp/epel-release-7-5.noarch.rpm


    - name: Add EPEL repository
      become: yes
      yum:
        name: /tmp/epel-release-7-5.noarch.rpm
        state: present



    - name: Add HDP repository
      become: yes
      get_url:
        url=http://public-repo-1.hortonworks.com/HDP/centos7/2.x/updates/2.4.0.0/hdp.repo
        dest=/etc/yum.repos.d/hdp.repo

    - name: Download HDP configuration files
      get_url:
        url=http://public-repo-1.hortonworks.com/HDP/tools/2.4.0.0/hdp_manual_install_rpm_helper_files-2.4.0.0.169.tar.gz
        dest=/home/vagrant/hdp_manual_install_rpm_helper_files-2.4.0.0.169.tar.gz
      tags: [test]

    - name: Extract HDP configuration files
      shell: tar xvfz /home/vagrant/hdp_manual_install_rpm_helper_files-2.4.0.0.169.tar.gz
      tags: [test]

    - name: Update cache
      become: yes
      yum:
        name=*
        update_cache=yes






