    - name: Creating myid file
      become: yes
      file:
        path={{ item }}/myid
        state=touch
        owner=zookeeper
        group=hadoop
        mode=0755
      with_items: "{{ZOOKEEPER_DATA_DIR.split(' ')}}"
      tags: [init_zookeeper]

    - name: Write znode_id in myid file
      become: yes
      become_user: zookeeper
      lineinfile:
        dest={{ item }}/myid
        line={{ znode_id }}
        state=present
        owner=zookeeper
        group=hadoop
        mode=0755
      with_items: "{{ZOOKEEPER_DATA_DIR.split(' ')}}"
      tags: [init_zookeeper]
