    - name: Create directory for storing the JobHistory server logs
      become: yes
      file:
        path={{ item }}
        state=directory
        owner=mapred
        group=hadoop
        mode=0755
        recurse=yes
      with_items: "{{MAPRED_LOG_DIR.split(' ')}}"
      tags: [hadoop_create_mapred_dirs]

    - name: Create directory for storing the JobHistory server PID
      become: yes
      file:
        path={{ item }}
        state=directory
        owner=mapred
        group=hadoop
        mode=0755
        recurse=yes
      with_items: "{{MAPRED_PID_DIR.split(' ')}}"
      tags: [hadoop_create_mapred_dirs]

